# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: insecure-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: insecure
#   template:
#     metadata:
#       labels:
#         app: insecure
#     spec:
#       containers:
#         - name: app
#           image: nginx:latest
#           securityContext:
#             privileged: true
#             runAsUser: 0
#           ports:
#             - containerPort: 80
